### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by hshreeshail** [thmoa/tex2shape#18]
Not an issue. Just a comment about opencv installation. Simply using `pip install opencv` leads to errors. That is because `python2.7 `support was dropped from `opencv=4.3.0.36` onwards.
Using `pip install opencv-python==4.2.0.32` worked for me.

Other errors I faced and how I solved them:
1] ERROR: 
```
Could not load dynamic library 'libnvinfer.so.6.
Cannot dlopen some GPU libraries. 
Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU.
```
SOLUTION: 
`pip install tensorflow==1.13.1`

2] ERROR:
```
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from models.tex2shape_model import Tex2ShapeModel
  File "/mnt/t-shingane/tex2shape/models/tex2shape_model.py", line 1, in <module>
    from keras.models import Model
  File "/mnt/envs/tex2shape/lib/python2.7/site-packages/keras/__init__.py", line 22, in <module>
    from keras import distribute
  File "/mnt/envs/tex2shape/lib/python2.7/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/mnt/envs/tex2shape/lib/python2.7/site-packages/keras/distribute/sidecar_evaluator.py", line 180
    f'No checkpoints appear to be found after {_CHECKPOINT_TIMEOUT_SEC} '
                                                                        ^
SyntaxError: invalid syntax
```
SOLUTION:
`pip install keras==2.3.0 `(I had initially just run `pip install keras` (as mentioned in README) which installed `keras 2.9.0` and was giving the aforementioned error)

**Comment by thmoa** [comment]
Thanks. Feel free to send a PR.
