### ISSUE TITLE
 thank you for you work

### ISSUE THREAD

**Issue by dayu1979** [thmoa/tex2shape#7]
Hello, thank you for you work, can you provide the requestment for runing the demo?
i use python3,but meet some error...

**Comment by IQ17** [comment]
This is based on python2 i think, as smpl is python2 only

**Comment by OOF-dura** [comment]
> This is based on python2 i think, as smpl is python2 only

Well. Can you post the requirement for running the demo?
I tried py2, but failed.
Many thanks!

**Comment by thmoa** [comment]
see `requirements.txt`

**Comment by OOF-dura** [comment]
> see `requirements.txt`

I checked my setting, in py3:
```
numpy                1.18.2
Keras                2.2.4
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
tensorboard          1.13.1
tensorflow-estimator 1.13.0
tensorflow-gpu       1.13.2
```
but still got error:
```
Traceback (most recent call last):
  File "run.py", line 109, in <module>
    main(args.image, args.iuv, args.out_dir, args.weights_tex2shape, args.weights_betas)
  File "run.py", line 61, in main
    pred = tex2shape_model.predict(unwrap)
  File "/home/frank/PycharmProjects/tex2shape/models/base_model.py", line 36, in predict
    return self.model.predict(x)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_1/convolution}}]]
         [[{{node output/BiasAdd}}]]
```

Actually, my current setting can run other deep learning code.

Can you help me? @thmoa 

Thanks!
```

**Comment by thmoa** [comment]
Sorry but I have no time to debug for you. If you find a bug, feel free to submit a PR.
The project is python2.

**Comment by OOF-dura** [comment]
> Sorry but I have no time to debug for you. If you find a bug, feel free to submit a PR.
> The project is python2.

ok! but wts the version of tensorflow?

**Comment by thmoa** [comment]
Try 1.11.0.
